### PR TITLE
updated docs structure

### PR DESCRIPTION
**Pull request by maxhirsch**
Changed src to api, added folders to api, and updated references in index.rst and docs/src.

### CODE REVIEW

**Review by lenghuang — CHANGES_REQUESTED** [review]
Would be helpful to give summary of changes in the PR description

**Comment by maxhirsch** [comment]
updated pr description

**Review by lenghuang — APPROVED** [review]
lgtm. I added a new line to `docs/_build/searchindex.js` for git formatting reasons

**Comment by lenghuang** [comment]
https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

Seems like PR's aren't set up with git actions to be automatically built. Check out the above to configure this.

**Pull request merged**
